/*
 * @Author: your name
 * @Date: 2021-10-12 18:47:44
 * @LastEditTime: 2021-10-13 14:14:45
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \RSA\RSA4096\RSA_4096_origin_private\main.c
 */
/*****************************************************************************
Filename    : main.c
Author      : Terrantsh (tanshanhe@foxmail.com)
Date        : 2018-9-25 11:19:48
Description : Rsa4096
*****************************************************************************/
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <stdlib.h>
#include "private.h"
// int private_enc_dec(){
// 	clock_t start, finish;
//     double  duration;
//     start = clock();

//     unsigned char input [256] = {0x22,0x21,0x12,0xed,0xf2};        // message to encrypt
//     private_encrypt(input);

//     char base64[] = "N0I2NzJENEM5QjM2REFCMzJBNUU3MkQxNUNBM0Y2MkI5RjY0RTAyRUExODJBNzkyQkE0MzA5OTdDREY0RjA1MjA2RDJDMkZFQThFRDNGMkY5OTRDOTM3MkQzRTI3MkY3NTMxMDg5MTgzRUQ1REJCMDAwQkNBQkZGRjRDMkE3MkNFMkM4NTI2QjdEQTY5MTQ2MzBFMTcxQzQyRUQ0RDcyODlDOTdBQUEwRjYxNTAwMkFCRUIyNDg2Q0NCMzVGQUFDQjg0QjI1Q0FGREQwOUZGRkE5OTE2RUNCOTVDQjc3N0Q0RjI1N0ZEODE1RDQzMkI1M0MyM0JBOTlGRUJBMUY3NDRDRTNGMDgxMzdGODBDMUMzRjczNjkzNUExNUNDRUEzMjE1ODRERTREQTUzNUI0OUM4NTMwQUExOUVGMzVGREQzMDlGMzQ3NkM4MzQ3MUJFQUMyNTVCMTM2RDg3NTc2OUYzNzg1MzY1RUM4RTcyOEUyMDUzQjBCNDc4ODU3N0U4NkQ5MUJGN0MwRDcxOEMzN0NCREEyQ0E2QUYwQTJCMDIwMUZFNUI4MUFGNDE2MEU2QzM2NTlCMDBGRTAwNkRFQTk3MzI0QjUwMTc0MERCNERGNUFERjFCQjY2OTMyMTE1RjZEMEVBODQ0MjZFRkQyRjIyMTkxRDk4RjMzODdFRUI5OTREMDA2QkY1RTU3M0QzRDhGNjBDQjM0OEQ1MkVFMDI1NjcwRUI5MEVCODJBMjIwQTg5MUM2MzJGMzUzMjdEQTg0QTYxNEJDODZCRTUwMDk5QTIxMzU2M0Q3NjU0Q0MyODNCQzdDNjkzQTBGNEEyOEY5QkRFM0JDMjI1OTY2RjE0N0VGQkMwMzhDMEY0MzkzNDc2RDM3ODRCQTZFRjY4MDBBRjQ1ODg2OTM4Q0RBMzAyM0I1NUFDOEQwNDZENDU3QUJFRTI0MzQ1RUVCNkY5RkY5NTNGQjcwQjYzREI2NTkxQzYyNEJBQzQ5OTBCOUZEMUUzMTc0MUFGMTBBNkVGRURBNUFCREI2NkVBNEQ3MDI5RjNCNzMzQTBCOEU3MkY2QUI3QjMxMjJBQ0Q1NTVGREI2ODk2MDM1OUUwODhCRUJBNkREMDIwMDk4NzVCREI3MzM1Mzg5QzJENEY4QjlFNTdFNjIyRDJBRjlFQzNENTg1RTc5MDQwQkUzRDRCMUVBMTAzODk1QTA3MDM1QjQ3QjJGQUI3MTMxOEQ5QkNBNjVEOUQ1RjQxMUQyMDA1ODg4QzQ3MkMzNTc2QjREMTNEMTdDQTk4OUMyNzM0REExQjkxRTFCQjI3NzQ4RUI2NzQwN0IxNENFRjFBODdDREQ5MDkxOEIwNDk0NkU0Njc1RA==";
//     private_decrypt(base64);

    
//     finish = clock();
//     duration = (double)(finish - start) / CLOCKS_PER_SEC;   // print the time about the process
//     printf( "%f seconds\n", duration );

//     return 0;
// }
// int public_enc_dec()
// {
//     clock_t start, finish;
//     double  duration;
//     start = clock();

//     unsigned char input [256] = {0x22,0x21,0x12,0xed,0xf2,0xde,0x54}; // message to encrypt
//     public_encrypt(input); // public key encrypt

//     char base64[] = "ODc1MDcwNkI4QkE5QkIxOUU5MkY5OENEQjU3OTQ2OEY2QjI5MTg4MjRFRjA1ODQyMEQ1RjhDOUFEMjBFRThFOENGNzQ1ODI5NDFGQ0Y1MzRCOTlERUJFQkI5Q0M5QUMwOEJBRTBCMjgyMEY4N0VDNDdCNjhGMUQ3QTkwRTI1QTdFRTdEMTcxMDQ2MjA5MzBBRTgwM0FCQzZFNTNDNTc2NTc2RTcyNkZCMDYyQ0JCNDRBMjAzMTcwM0QwOTZFMjVDNjY3NEYzODA1RUM2MjBDRERGMzlFREVENUM3QjkyNzYyRjcxMkE0MzhBQjI3Q0U4QUYwMjk1NjNGNkM1QUQzNUJGOTI2QkIwM0I1RDQ4ODQxRkQzNDJBNjI3RkFGRkFCREIyNkU0QTFCOEY5QkFDRDdCOTU5OEE3RkI5MDczMkU3MTI5RjM5MTJERTBFNjk0NUYzRkNFRUQyMUM3RDMwRDY0NTU2MUM2M0IzQkQ1MDNEOUYwNTQ2Q0MzQjg4MDVGM0Q3QjQ4MzZDQTVCQ0ZFRDM4ODZENjUxQkExQzhEQ0IwQTEzMTEyQkYxNjdEOTU2MkQwNzQ1QTMxQkFBODE1OEVBMzQyRjY4NjAzNDBDQzRDREQ1N0FFQTQzMTJCMEM0QTZFNTRDNUE2NUI0RTlGREM3MjlBQzIyQTREQzI0QjdENDZGRTlENzhCMjQxNjU0NzM5NTAzOEY0MEM3NjQyQkNFM0QyOTExNDlCRkY3RUYyMUQ2QjU5MUU5NTVFN0MxN0MxMEY3QUFBRDA5OThFREIwQTUxQkVERDE5MzNCMTFGMjk1MDI0MjIzQzVGM0I3MUE2NjlEMDhBM0IyMTZEN0IyQTIzNkQyMUYzNkQxMzYzOUU2Q0ZBM0IyNTZEMjAyQTA2OTk3RTU5NzY2N0UzODcwM0Y5RDU5M0VBRTdBRDZCNDBEMDk2QUU1MzM0RkI2NzQyNTJCN0QwOUVDNUNBMzVGNDVEOTBGMDJCMzg4ODVFRkYwNjBFQUMyMDc5QTk3MzIyQ0UwNjE2RkJDNDFCNTYzRUUzNDlFMUE4RTI3RTU2M0E3Q0UzQjdBNDJFQUQ1M0UyQTFGQjRFN0MwMjQ5RjVDNUExQjcwRTA3QzM1MjQwMjMzODVCRTM2NDNCMkQxMjE1ODQ5OEUzMDBGOEY0MDE5OTI2REQ4RkFGODY2Njc2NDY4MUZFMDRENUEwQTNEOUYxMDNGOEE5MkI4QjFEMzgxRTI4MzJFODEyOTBDQ0ZCQjQ4QzkwMjBGRjJEODVEMDQzMjUzM0I2NjczN0QwNENDMDczMjQyREIyMTdBRjJDQ0IwRDYyNUFCQkE4M0I1MjE1OEQ2NEU4NjQ4RkM0RA==";
//     public_decrypt(base64); // private key decrypt

//     finish = clock();
//     duration = (double)(finish - start) / CLOCKS_PER_SEC;   // encrypt or decrypt time used
//     printf( "%f seconds\n", duration );

//     return 0;
// }
int main(int argc, char const *argv[])
{
    private_enc_dec_test();
	// public_enc_dec();
}
